---
 - name: Install and configure tomcat
   hosts: slaves
   gather_facts: false
   become: yes
   tasks:
     - name: installing java      
       apt:
         name: openjdk-8-jdk
         state: present

